elasticsearch
Sultanow/js_menus pull request #23
Opened 2020-07-26 12:36 UTC by georgos987

2020-09-22 15:10 UTC, schnappinger requested changes
Sieht schon ganz gut aus. Allerdings muss die REST-Schnittstelle nochmal überarbeitet werden.

2020-09-22 15:10 UTC, schnappinger commented on backend/src/main/java/de/jsmenues/backend/elasticsearch/service/HistoryServiece.java
> +    public static String deleteHistoryRecordsBydate() throws IOException {
Der Methodenname ist irreführend.

2020-09-22 15:43 UTC, georgos987 commented on backend/pom.xml
> +      <artifactId>httpclient</artifactId>
ja , es ist erforderlich

2020-09-22 15:47 UTC, georgos987 commented on backend/src/main/java/de/jsmenues/backend/elasticsearch/controller/ElasticsearchController.java
> +    @Path("/indexname")
wie meinst du das?

2020-09-22 15:51 UTC, georgos987 commented on backend/src/main/java/de/jsmenues/backend/elasticsearch/controller/InformationHostController.java
> +@Path("/elasticsearch")
Ja, elasticsearch alein als Endpoint führt zu gar nichts

2020-09-22 15:55 UTC, georgos987 commented on backend/src/main/java/de/jsmenues/backend/elasticsearch/service/HistoryServiece.java
> +    public static String deleteHistoryRecordsBydate() throws IOException {
deleteHistoryRecordsBetweenTowDate()?? als Vorschlag

2020-09-23 07:03 UTC, schnappinger commented on backend/src/main/java/de/jsmenues/backend/elasticsearch/controller/ElasticsearchController.java
> +    @Path("/indexname")
vermutlich, dass du eine Search auf den Indexname machst, ohne es als Search zu bezeichnen. Aber darüber können wir evtl. bei einem Redesign der Schnittstelle noch mal sprechen.

2020-09-23 07:05 UTC, schnappinger commented on backend/src/main/java/de/jsmenues/backend/elasticsearch/service/HistoryServiece.java
> +    public static String deleteHistoryRecordsBydate() throws IOException {
Es geht darum, dass du angibst, dass etwas anhand eines Datums gelöscht wird. Allerdings wird kein Datum mitgegeben.

2020-09-23 07:07 UTC, schnappinger commented on backend/src/main/java/de/jsmenues/backend/elasticsearch/controller/InformationHostController.java
> +@Path("/elasticsearch")
Es geht darum, dass du mehrere Controller hast, die den Pfad ``elasticsearch`` verwenden. Dies kann dazu führen, dass Pfade doppelt belegt werden.

2020-09-24 15:15 UTC, georgos987 commented on backend/src/main/java/de/jsmenues/backend/elasticsearch/controller/HistoryController.java
> +@Path("/elasticsearch")
gib mir hier bitte ein Vorschlag 
("/elasticsearch/history/")
oder 
("/elasticsearchHistory/")

2020-09-24 15:19 UTC, schnappinger commented on backend/src/main/java/de/jsmenues/backend/elasticsearch/controller/HistoryController.java
> +@Path("/elasticsearch")
``/elasticsearch/history/``

2020-09-29 13:37 UTC, schnappinger approved these changes
Passt so

2020-09-30 09:24 UTC, merged